fxhash/fxhash-website

src/components/Activity/Action.module.scss
src/components/Activity/Action.tsx
src/components/Features/Feature.tsx
src/containers/User/UserHeader.module.scss
src/containers/User/UserHeader.tsx
src/pages/generative/[id]/collection.tsx
src/pages/objkt/[...params].tsx
src/utils/units.ts

Changed wording and layout of GT action component for legibility & scan.

Tweaks to GT action component

---

src/components/Utils/ContractsOpened.tsx
src/utils/schedule.ts

When the mint is closed, display when it will be next open (in the top bar)

✨ show next open time when mint is closed

---

src/components/Button/Button.module.scss
src/components/Button/index.tsx
src/components/Exploration/FiltersPanel.module.scss
src/components/Input/InputRadioButtons.module.scss
src/components/Search/Search.module.scss
src/components/Search/SearchHeader.tsx
src/containers/ExploreGenerativeTokens.tsx
src/containers/Generative/GenerativeFilters.module.scss
src/containers/Generative/GenerativeFilters.tsx
src/containers/Marketplace.tsx
src/pages/explore.tsx
src/services/ApolloClient.ts
src/types/entities/GenerativeToken.ts

Implements:
* https://github.com/fxhash/fxhash-website/issues/22

✨ added sort/filter options to the explore page

---

src/components/Card/Card.module.scss
src/components/Card/Card.tsx
src/components/Card/CardLoading.module.scss
src/components/Card/CardLoading.tsx
src/components/Card/ObjktCard.module.scss
src/components/Card/ObjktCard.tsx
src/components/Input/InputMultiList.module.scss
src/components/Input/InputMultiList.tsx
src/components/List/ListItemGenerative.module.scss
src/components/List/ListItemGenerative.tsx
src/containers/User/UserCollection.tsx
src/containers/User/UserCollectionFilters.module.scss
src/containers/User/UserCollectionFilters.tsx
src/containers/User/UserHeader.module.scss
src/containers/User/UserHeader.tsx
src/containers/User/UserModeration.tsx
src/queries/user.ts
src/services/ApolloClient.ts
src/types/entities/User.ts
src/utils/array.ts

Implements
* https://github.com/fxhash/fxhash-website/issues/25
* https://github.com/fxhash/fxhash-website/issues/26

Add sort/filters to the user collection

---

src/components/MessageCenter/Message.module.scss
src/components/MessageCenter/Message.tsx
src/components/MessageCenter/MessageCenterContainer.module.scss
src/components/MessageCenter/MessageCenterContainer.tsx
src/containers/Root.tsx
src/context/Cycles.tsx
src/context/MessageCenter.tsx
src/styles/globals.scss

* https://github.com/fxhash/fxhash-website/issues/48

✨ message center, succes error warning

---

src/containers/Token/Edit/EditPricing.tsx
src/queries/generative-token.ts
src/types/entities/GenerativeToken.ts

* https://github.com/fxhash/fxhash-website/issues/71

✨ added warning against re-sceduling abuse

---

src/components/Utils/Countdown.tsx
src/containers/Community/ScheduleLine.tsx
src/context/Cycles.tsx
src/utils/schedule.ts

Add support for (AND+OR) operators on the cycles

---

src/context/MessageCenter.tsx

> * fix [Make the user collection enjoy fetch the whole collection #73](https://github.com/fxhash/fxhash-website/issues/73)

fix bug multiples messages not clear

---

src/components/Layout.tsx
src/components/Layout/Warning.module.scss
src/components/Layout/Warning.tsx

fix: top warning message space adapt to its content

---

src/containers/Stats/Ranks/CollectionRanks.tsx

Add all time to marketplace rankings

---

src/components/Activity/Activity.tsx
src/components/Skeleton/Skeleton.tsx
src/components/Skeleton/index.tsx
src/containers/Generative/Actions.tsx
src/containers/User/UserActions.module.scss
src/containers/User/UserActions.tsx

feat(activity): change loader component by skeletons blocks

---

src/containers/Generative/Enjoy/GenerativeEnjoy.module.scss
src/containers/Generative/Enjoy/GenerativeEnjoy.tsx

I implemented the randomization pretty much as described in the issue using `useMemo`. Should the cursor reset when randomization is reset? 
- fix #87

Add randomization feature for enjoy

---

src/containers/Generative/Display/GenerativeDisplay.tsx

add toggeable to mobile EntityBadge

---

src/containers/Generative/Iterations/GenerativeIterations.tsx

feat(generative-token): iterations can be sort by price

---

src/containers/ExploreGenerativeTokens.tsx
src/containers/Generative/Iterations/GenerativeIterations.tsx
src/containers/Generative/Iterations/GenerativeIterationsFilters.tsx
src/containers/Marketplace/Collections.tsx
src/queries/generative-token.ts
src/services/ApolloClient.ts
src/types/entities/Objkt.ts
src/utils/filters.ts

feat(generative-token): add a filter 'listings > all | for sale'

---

src/components/Stats/GenerativeRank.module.scss

fix(marketplace): in rankings, long one word author and title now break-word

---

src/services/contract-operations/ListingAccept.ts
src/services/contract-operations/Offer.ts
src/services/contract-operations/OfferAccept.ts
src/services/contract-operations/OfferCancel.ts
src/types/entities/Offer.ts

Added offer, offer_accept & offer_cancel contract operations

---

src/components/Article/ArticleContent.module.scss
src/components/Card/Card.tsx
src/components/Card/CardList.module.scss
src/components/Card/GenerativeTokenCardList.module.scss
src/components/Doc/DocHomeCategory.module.scss
src/components/Doc/DocHomeCategory.tsx
src/components/Input/Select.module.scss
src/components/Input/Select.tsx
src/components/Layout/Spacing.module.scss
src/components/Layout/Spacing.tsx
src/containers/Marketplace/GenerativeStatsMarketplace.module.scss
src/containers/Marketplace/GenerativeStatsMarketplace.tsx
src/containers/Planning/Planning.module.scss
src/containers/Planning/Planning.tsx
src/containers/Settings/DisplaySettings.module.scss
src/containers/Settings/Settings.module.scss
src/containers/User/UserHeader.module.scss
src/containers/User/UserProfileLayout.tsx
src/pages/community/opening-schedule.tsx
src/pages/community/reports.tsx
src/pages/doc.tsx
src/pages/doc/[category]/[article].tsx
src/pages/explore/reveal-feed.tsx
src/pages/index.tsx
src/pages/marketplace/generative/[id].tsx
src/pages/sandbox.tsx
src/styles/Home.module.scss

fixes #20 #95 
I made sure all data is clear to read / fix any layout bugs. 
Didn't take any opinionated responsive style (a designer or a design validation would be best before)

fix(styles): multiple responsive fixes

---

src/components/TableUserSales/TableUserSales.tsx
src/containers/User/UserSalesTable.tsx
src/utils/entities/actions.ts

User dashboard sales now handles OFFER_ACCEPTED

---

src/components/Activity/Action.module.scss
src/components/Activity/Action.tsx

Add action components for OFFER actions

---

src/components/TableUserSales/index.ts
src/components/Tables/TableOffersReceived.tsx
src/components/Tables/TableOffersSent.tsx
src/components/Tables/TableUser.module.scss
src/components/Tables/TableUserSales.tsx
src/components/Tables/index.ts
src/containers/User/UserDashboard.tsx
src/containers/User/UserOffersReceived.tsx
src/containers/User/UserOffersSent.tsx
src/containers/User/UserSales.tsx
src/queries/user.ts
src/types/entities/User.ts

require merge #166 
fixes #150 
Also fix sales doesn't trigger fetch more when there is nothing to fetch

feat(user): add table offers received / sent

---

src/components/Navigation.tsx

feat(nav): add dashboard url 

---

package-lock.json
package.json
src/components/Input/Dropzone.tsx
src/components/Input/InputSplits.tsx
src/components/Input/Reserves/InputReserveWhitelist.module.scss
src/components/Input/Reserves/InputReserveWhitelist.tsx
src/components/ModalImportCsv/ModalImportCsvReserve.module.scss
src/components/ModalImportCsv/ModalImportCsvReserve.tsx
src/components/Utils/Modal.module.scss
src/utils/csv.ts

fixes #139 
files used for test:
[test.csv](https://github.com/fxhash/fxhash-website/files/8778653/test.csv)
[test-bug.csv](https://github.com/fxhash/fxhash-website/files/8778651/test-bug.csv)
[test-bug2.csv](https://github.com/fxhash/fxhash-website/files/8778652/test-bug2.csv)
Handle long list, missing columns, duplicates, bad tezos address.

feat(reserve): add import from csv file for reserves 

---

src/pages/pkh/[id]/dashboard/[[...tab]].tsx

replicate change from /u to /pkh

fix: pkh can access dashboard from user dropdown menu

---

src/components/Card/CardNFTArticle.module.scss
src/components/Card/CardNFTArticle.tsx
src/components/Card/CardNFTArticleSkeleton.tsx
src/containers/Explore/ExploreArticles.module.scss
src/containers/Explore/ExploreArticles.tsx
src/containers/Explore/ExploreTabs.tsx
src/pages/explore/articles.tsx
src/queries/articles.ts
src/queries/fragments/article.ts
src/queries/fragments/user.ts
src/services/ApolloClient.ts
src/styles/Effects.module.scss
src/styles/globals.scss
src/types/Article.ts
src/types/Metadata.ts
src/types/entities/Article.ts

feat(explore): add articles list

---

src/components/NFTArticle/NFTArticle.module.scss
src/components/NFTArticle/SlateEditor/AutoFormatPlugin/index.tsx
src/components/NFTArticle/SlateEditor/ImagePlugin/SlateImagePlugin.ts
src/components/NFTArticle/SlateEditor/index.tsx
src/components/NFTArticle/elements/Figcaption.tsx
src/components/NFTArticle/elements/Figure.tsx
src/components/NFTArticle/elements/ImageElement.module.scss
src/components/NFTArticle/elements/ImageElement.tsx
src/components/NFTArticle/processor.ts
src/containers/Article/Editor/ArticleEditor.module.scss
src/containers/Article/Editor/ArticleEditor.tsx

Images can be dropped & pasted into the editor

---

src/components/Medias/ImagePolymorphic.tsx
src/components/NFTArticle/SlateEditor/HotkeyPlugin/HotkeyPlugin.tsx
src/components/NFTArticle/SlateEditor/Plugins/SlateConstraintsPlugin.ts
src/components/NFTArticle/SlateEditor/Plugins/SlateImagePlugin.ts
src/components/NFTArticle/SlateEditor/Plugins/SlateMediaPlugin.ts
src/components/NFTArticle/SlateEditor/index.tsx
src/components/NFTArticle/elements/ImageElement.tsx
src/containers/Article/Editor/ArticleEditor.module.scss
src/containers/Article/Editor/ArticleEditor.tsx
src/containers/Article/Editor/EditorMedia.tsx
src/containers/Article/Editor/EditorMedias.module.scss
src/containers/Article/Editor/EditorMedias.tsx
src/pages/editor/edit.tsx
src/services/apis/file-api.service.ts
src/types/ArticleEditor/Editor.ts
src/types/ArticleEditor/Image.ts
src/utils/array.ts
src/utils/files.ts
src/utils/ipfs.ts

Keep track of medias and medias upload

---

src/components/Tables/TableOffersReceived.tsx

fix(dashboard): offers floor don't throw error anymore

---

src/components/Card/CardNFTArticle.module.scss
src/components/Card/CardNFTArticle.tsx
src/components/Card/CardNFTArticleSkeleton.tsx
src/containers/User/UserArticles.module.scss
src/containers/User/UserArticles.tsx
src/containers/User/UserProfileLayout.tsx
src/pages/pkh/[id]/articles.tsx
src/pages/u/[name]/articles.tsx
src/queries/user.ts
src/types/entities/User.ts

feat(user): add articles tab to user profile

---

src/components/Card/CardNFTArticle.module.scss
src/components/Card/CardNFTArticle.tsx
src/components/Navigation.tsx
src/containers/Article/Editor/ArticleEditor.tsx
src/containers/Article/LocalArticles.module.scss
src/containers/Article/LocalArticles.tsx
src/containers/User/UserArticles.tsx
src/pages/pkh/[id]/articles.tsx
src/pages/u/[name]/articles.tsx
src/services/ServerSideProps/ServerSidePropsUser.ts
src/types/ArticleEditor/Editor.ts
src/types/entities/Article.ts

require merge PR #221 and #241 
fix #200 
the behavior is fully functional, style/UX might have to be reworked:
- style of button of "create article" in user connected profile
- autosave fixed box currently display informations when: 
- - any changes is unsaved
- - any media is not uploaded 
- - when it's auto-saving
- - what time it has been saved

feat(user): show local article drafts, cta to create new draft, link in menu to go to articles

---

src/components/NFTArticle/NFTArticle.module.scss
src/components/NFTArticle/NFTArticle.tsx
src/components/NFTArticle/elements/Embed/EmbedSpotify.tsx
src/components/NFTArticle/elements/Embed/EmbedYoutube.tsx
src/components/NFTArticle/elements/Medias/NFTArticleImage.tsx
src/components/NFTArticle/elements/Table/TableEditor.module.scss
src/components/NFTArticle/elements/TezosStorage.module.scss
src/components/NFTArticle/elements/TezosStorage.tsx
src/components/NFTArticle/processor/getNFTArticleComponentsFromMarkdown.ts
src/containers/Article/PageArticle.module.scss
src/containers/Article/PageArticle.tsx
src/queries/fragments/article.ts

Style of the article

---

package.json
src/components/NFTArticle/elements/Embed/Embed.module.scss
src/components/NFTArticle/elements/Embed/EmbedEditor.tsx
src/components/NFTArticle/elements/Embed/EmbedMedia.tsx
src/components/NFTArticle/elements/Embed/EmbedTwitter.tsx
src/utils/embed.ts
yarn.lock

feat(article): add embed media twitter

---

src/components/NFTArticle/SlateEditor/Elements/Blocks.tsx
src/components/NFTArticle/processor/getSlateEditorStateFromMarkdown.ts
src/components/NFTArticle/processor/plugins.ts

feat(article): unwrap listItem for slate

---

src/components/Card/CardNFTArticle.module.scss
src/components/SortAndFilters/SortAndFilters.tsx
src/containers/Explore/ExploreArticles.tsx
src/containers/ExploreGenerativeTokens.tsx
src/hooks/useFilters.ts
src/hooks/useSort.ts
src/pages/delete-for-prod/article.tsx
src/pages/delete-for-prod/editor.tsx
src/pages/explore/articles.tsx
src/queries/articles.ts
src/types/entities/Article.ts
src/utils/sort.ts

fixes fxhash/fxhash-website#284
also add refacto to sort and filters

feat(articles): add sort and search to article

---

src/components/Card/CardNFTArticle.module.scss
src/components/Card/CardNFTArticle.tsx
src/containers/Article/LocalArticles.tsx

Draft articles can be removed

---

src/pages/article/editor/local/new.tsx

Wrong url pushed to router when previewing fresh article

---

src/pages/article/editor/local/[id]/preview.tsx

Article preview, reducing splits keeps user not found with the API

---

src/components/NFTArticle/SlateEditor/Elements/Blocks.tsx
src/components/NFTArticle/SlateEditor/Utils/BlockMenu.module.scss
src/components/NFTArticle/SlateEditor/Utils/BlockMenu.tsx

fix(article): block menu hide correctly on firefox, block menu doesnt flash position on init

---

src/containers/Article/Editor/ArticleEditor.module.scss
src/containers/Article/Editor/ArticleEditor.tsx
src/containers/Article/Editor/AutosaveArticle.module.scss
src/containers/Article/Editor/AutosaveArticle.tsx

* resolve #314 
* moved to bottom right & lighter design
* changed behavior to improve clarity
* added clickable medias error to move to the block

Improved autosave tooltip ui/ux

---

src/components/NFTArticle/SlateEditor/Elements/RenderElements.module.scss
src/components/NFTArticle/SlateEditor/Elements/RenderElements.tsx

* resolve #315 
* lower part of buttons is clickable
* buttons are shown when the block is focused

Show buttons when block is focused

---

src/components/Card/CardNFTArticle.module.scss
src/components/Card/CardNFTArticle.tsx
src/components/Guards/UserGuard.tsx
src/components/List/ListSplits.tsx
src/components/Utils/Date/DateFormat.tsx
src/containers/Article/ArticleInfos.tsx
src/containers/Article/Edition/ArticleEdition.tsx
src/containers/Article/Edition/ArticleEditionPreview.tsx
src/containers/Article/Edition/ButtonsEditArticle.module.scss
src/containers/Article/Edition/ButtonsEditArticle.tsx
src/containers/Article/Editor/ArticleEditor.tsx
src/containers/Article/Editor/AutosaveArticle.tsx
src/containers/Article/Infos/ArticleRevisions.module.scss
src/containers/Article/Infos/ArticleRevisions.tsx
src/containers/Article/LocalArticles.tsx
src/containers/Article/PageArticle.module.scss
src/containers/Article/PageArticle.tsx
src/containers/User/UserArticles.tsx
src/context/Articles.tsx
src/pages/article/editor/[id]/index.tsx
src/pages/article/editor/[id]/preview.tsx
src/pages/article/id/[id].tsx
src/queries/fragments/article.ts
src/services/ServerSideProps/ServerSidePropsArticle.ts
src/types/ArticleEditor/Editor.ts
src/types/entities/Article.ts
src/utils/generative-token.ts
src/utils/math.ts
src/utils/nft-article.ts
src/utils/user.ts

* resolve #291 
* resolve #292

Articles edition

---

src/articles/nft-article-test.md
src/components/NFTArticle/SlateEditor/Blocks.tsx
src/components/NFTArticle/SlateEditor/Plugins/AutoFormatPlugin/index.tsx
src/components/NFTArticle/elements/TezosStorage/TezosStorageDisplay.tsx
src/components/NFTArticle/elements/TezosStorage/TezosStorageEditor.tsx
src/components/NFTArticle/elements/TezosStorage/TezosStorageGentk.tsx
src/components/NFTArticle/elements/TezosStorage/TezosStorageProject.tsx
src/components/NFTArticle/processor/getMarkdownFromSlateEditorState.ts
src/components/NFTArticle/processor/getNFTArticleComponentsFromMarkdown.ts
src/components/NFTArticle/processor/plugins.ts
src/containers/Article/Editor/AutosaveArticle.tsx
src/doc/community/articles.md
src/services/LocalFiles.ts
src/types/TezosStorage.ts
src/utils/tezos-storage.ts

Implement changes made to tezos-storage-pointer spec

---

src/containers/User/UserArticles.tsx
src/services/ApolloClient.ts

fix(user): articles load correctly without infinite loop

---

src/utils/entities/articles.ts

fix(article): invalid slug with just a dot redirect to id

---

src/components/NFTArticle/elements/List/ListDefinition.tsx
src/containers/Article/Editor/AutosaveArticle.tsx

fix(article): add break in a list only convert to paragraph at the end of the list

---

src/components/Button/Button.module.scss
src/components/Button/index.tsx
src/components/Card/CardNFTArticle.module.scss
src/components/Card/CardNFTArticle.tsx
src/components/Input/Select.module.scss
src/components/Layout/Tabs.module.scss
src/components/Layout/Tabs.tsx
src/containers/User/Collection/Articles.module.scss
src/containers/User/Collection/Articles.tsx
src/containers/User/Collection/Gentks.module.scss
src/containers/User/Collection/Gentks.tsx
src/containers/User/UserCollection.module.scss
src/containers/User/UserCollection.tsx
src/containers/User/UserProfileLayout.tsx
src/pages/pkh/[id]/collection.tsx
src/pages/pkh/[id]/collection/articles.tsx
src/pages/u/[name]/collection.tsx
src/pages/u/[name]/collection/articles.tsx
src/queries/user.ts
src/types/entities/Article.ts

- fix #376
Implemented as described in #376. 
@ciphrd For now we are just fetching objkts and articles owned in parallel independent of the selected tab. what do you think?
Link: http://localhost:3000/u/fxhash%20admin/collection/articles
Link: http://localhost:3000/u/fxhash%20admin/collection

Feature/marketplace-v3:  Add articles to user collection

---

src/components/NFTArticle/NFTArticle.module.scss
src/components/NFTArticle/elements/Image/ImageAttributeSettings.tsx
src/components/NFTArticle/elements/TezosStorage/TezosStorageDisplay.module.scss
src/components/NFTArticle/elements/TezosStorage/TezosStorageGentk.module.scss
src/components/NFTArticle/elements/TezosStorage/TezosStorageGentk.tsx
src/components/NFTArticle/elements/Video/VideoAttributeSettings.tsx
src/containers/Article/Editor/ArticleEditor.tsx
src/containers/Article/PageArticle.module.scss

fix(article): update media size (video, image)

---

package.json
src/components/Card/CardNFTArticle.tsx
src/components/NFTArticle/elements/Link/LinkDefinition.tsx
src/containers/Article/Editor/AutosaveArticle.module.scss
src/containers/Article/Editor/AutosaveArticle.tsx
src/context/Articles.tsx
src/utils/strings.ts
src/utils/window.ts
yarn.lock

fix #374 
Many checks to prevent problems

fix(article): autosave warn user if using incognito mode, check that an article saved correctly, check localStorage is available

---

src/components/NFTArticle/elements/Embed/EmbedYoutube.tsx

fix(article): embed youtube need allow-presentation to work properlly

---

src/components/Medias/VideoPolymorphic.tsx
src/components/NFTArticle/elements/Video/VideoDisplay.tsx
src/components/NFTArticle/elements/Video/VideoEditor.tsx

fix(article): media video dont crash page when url is wrong

---

src/containers/Article/Edition/ArticleEditionPreview.tsx
src/containers/Article/Edition/ButtonsEditArticle.tsx
src/containers/Article/Editor/ArticleEditor.tsx
src/containers/Article/PageArticle.tsx
src/utils/nft-article.ts

added a temporary solution for thumbnail update while indexer get fixed -> this is the task to remove the temporary solution #392

fix(article): thumbnail update correctly, don't throw error on edition

---

.gitignore

A small change to .gitignore to avoid pushing IDE-related files from Intellij Idea to the repo (IDE that I use)

style(project): ignore IDEA files from intellij idea

---

src/containers/Article/Editor/ArticleEditor.tsx

Copywriting hotfix based on Charlie's ask

fix(article): remove 'soon to be collected' copy in numbers of editions

---

src/components/Card/CardNFTArticle.tsx
src/containers/Article/ArticleInfos.module.scss
src/containers/Article/ArticleInfos.tsx
src/containers/Article/LocalArticles.tsx
src/containers/Article/PageArticle.module.scss
src/containers/Article/PageArticle.tsx
src/queries/fragments/article.ts
src/services/contract-operations/LockArticle.ts
src/types/entities/Article.ts

- fix #355 
@ciphrd should we mark locked articles for users too? e.g. on the card?

Feature/Articles: Add button to lock meta data

---

src/containers/User/UserArticles.tsx
src/pages/collaborations/[address]/index.tsx
src/pages/community/reports.tsx
src/pages/edit-generative/[id].tsx
src/pages/generative/[...params].tsx
src/pages/generative/[id]/enjoy.tsx
src/pages/gentk/[...params].tsx
src/pages/index.tsx
src/pages/live-minting/[id]/generative/[tokenId].tsx
src/pages/live-minting/[id]/reveal/[number]/[hash].tsx
src/pages/marketplace/generative/[id].tsx
src/pages/reveal/[id]/[hash].tsx
src/services/ApolloClient.ts
src/services/ServerSideProps/ServerSidePropsArticle.ts
src/services/ServerSideProps/ServerSidePropsUser.ts

on server a new client must be created to ensure serving latest data to users.
- fix #396

refactor apollo client singleton to new instance

---

src/utils/user.ts

feat: add donation address savepakistan

---

src/containers/Article/Infos/ArticleQuickCollectAction.tsx
src/containers/Article/PageArticle.module.scss
src/containers/Article/PageArticle.tsx

feat(article): add buy button on top of article

---

src/containers/Generative/ExtraActions.tsx
src/services/Wallet.ts

fix(contract): report contract works

---

src/components/Image/Image.module.scss
src/components/Image/index.tsx

fix bug related to loading square flashing in image components

fix: image component get border-radius inherit

---

src/context/Theme.tsx

fix: dark mode is applied on body instead of nested div, which fix theme issues within react portal

---

src/pages/search/[[...params]].tsx

decode search query string

---

src/components/Image/index.tsx

fix(image): pixel density used is maximum 2, maximum thumbnail size used is 1400px

---

src/components/Collaborations/Proposal/Details/UpdateIssuer.tsx
src/components/GenerativeToken/Reserves/ReserveAccessList.tsx

Access list now show correctly the user name

fix: users query variable fixed for access list and collab

---

src/components/Exploration/FiltersPanel.tsx
src/components/Layout/MobileMenu.tsx
src/components/Layout/Navigation.tsx
src/components/Utils/Modal.module.scss
src/components/Utils/Modal.tsx
src/context/Theme.tsx
src/pages/_app.tsx
src/styles/globals.scss

feat: prevent body scrollable when a modal is open

---

src/components/Utils/Date/DateDistance.tsx
src/utils/tezos.ts

feat: add title to date distance

---

src/utils/user.ts

add tezos for iran to donation list

---

src/components/Button/Button.module.scss
src/components/Button/index.tsx
src/components/Carousel/Carousel.module.scss
src/components/Carousel/Carousel.tsx
src/components/Stats/GenerativeRank.module.scss
src/components/Stats/Ranks.module.scss
src/components/Stats/Ranks.tsx
src/containers/Stats/Ranks/CollectionRanks.module.scss
src/containers/Stats/Ranks/CollectionRanks.tsx
src/utils/array.ts

feat: marketplace pagination, arrows on desktop, touch on mobile

---

src/components/Image/index.tsx
src/components/Input/ProjectHolders/ProjectHolders.tsx
src/components/List/ListItemGenerative.module.scss
src/components/List/ListItemGenerative.tsx
src/components/Logo/LogoEffect.ts
src/components/NFTArticle/elements/TezosStorage/TezosStorageGentk.tsx
src/components/NFTArticle/elements/TezosStorage/TezosStorageSettings.module.scss
src/components/NFTArticle/elements/TezosStorage/TezosStorageSettings.tsx
src/containers/Article/ArticleActivity.tsx
src/containers/Article/PageArticle.tsx
src/containers/Generative/Actions.tsx
src/containers/Generative/ExploreIncoming.tsx
src/containers/User/UserProfileLayout.tsx
src/pages/generative/[...params].tsx
src/pages/generative/[id]/enjoy.tsx
src/pages/gentk/[...params].tsx
src/pages/index.tsx
src/pages/live-minting/[id]/generative/[tokenId].tsx
src/pages/marketplace/generative/[id].tsx
src/pages/pkh/[id]/collection/enjoy.tsx
src/pages/u/[name]/collection/enjoy.tsx
src/queries/articles.ts
src/queries/generative-token.ts
src/queries/marketplace.ts
src/queries/objkt.ts
src/queries/user.ts

- fix #441 
@ciphrd made another pass on the whole app. i fixed all placed you mentioned in the issue. i refactored all queries define in components into the `queries` folder and use the right fragments there. I also added the `<Image />` component to the `TezosStorage` element in the articles. 
I am not sure if you already thought about it, but how shall we handle images in the articles? Can we do that at all?
Should I also refactor the query from the `LiveMintingEvent` container? Do we actually have `captureMedia` on them?
https://github.com/fxhash/fxhash-website/blob/cdb5153c6a4f727db4def5e480a3a171c2956929/src/containers/LiveMinting/LiveMintingEvent.tsx#L14-L40

Fix missing image media entities

---

src/containers/Input/Donations.module.scss
src/hooks/useMintingState.ts
src/utils/user.ts

feat: add new donations addresses

---

src/containers/Objkt/ListingCreate.tsx

feat: add warning when listing under 50% of the floor

---

src/components/List/ListItemGenerative.tsx
src/containers/User/UserCollectionFilters.tsx

feat: sort user collection filters artist and generator alphabetically

---

src/components/NFTArticle/elements/Link/LinkElement.tsx

feat: add rel to article links depending of domain

---

src/utils/user.ts

Add new donation address as per discord request

feat: add donation address for cure parkinson's

---

src/queries/fragments/listing.ts

fix(marketplace): marketplace hide nswf content when toggled

---

package-lock.json
src/components/Card/Card.tsx
src/components/Card/CardsContainer.tsx
src/components/Card/GenerativeTokenCard.module.scss
src/components/Card/GenerativeTokenCard.tsx
src/components/GenerativeToken/MintingState/MintingStateTimer.module.scss
src/components/GenerativeToken/MintingState/MintingStateTimer.tsx
src/components/Layout/SectionHeader.tsx
src/components/Layout/Tabs.module.scss
src/components/Utils/Countdown.tsx
src/containers/Explore/ExploreTabs.module.scss
src/containers/Explore/ExploreTabs.tsx
src/containers/Explore/LiveFeed.tsx
src/containers/Generative/ExploreIncoming.module.scss
src/containers/Generative/ExploreIncoming.tsx
src/pages/explore.tsx
src/pages/explore/articles.tsx
src/pages/explore/incoming.tsx
src/pages/explore/reveal-feed.tsx
src/queries/generative-token.ts
src/utils/date-separator.ts

feat: redesign incoming page

---

src/components/Activity/ActionDefinitions.ts

previously was displayed wrongly as listing
- fix #541

Display OFFER_CANCELED as OfferCancelled

---

src/services/ServerSideProps/ServerSidePropsUser.ts

fix typo in new account description

---

src/containers/EditProfile.module.scss
src/containers/EditProfile.tsx

feat: add warning msg about tzProfiles on profile page

---

src/containers/User/Collection/Articles.tsx
src/containers/User/Collection/Gentks.tsx
src/containers/User/UserGenerativeTokens.tsx
src/containers/User/UserListings.tsx

feat(user): add info message when a gallery / container is empty

---

src/components/Layout/navigationLinks.ts

as agreed with qaulv on discord, adding a shortcut to the profile dropdown to emphase on the article creation

feat: add 'mint article' in the profile nav'

---

src/components/CreditCard/WinterCheckout.tsx
src/components/GenerativeToken/MintButton.tsx
src/components/GenerativeToken/MintController.tsx
src/components/Utils/ButtonPaymentCard.module.scss
src/components/Utils/ButtonPaymentCard.tsx
src/containers/Objkt/ListingAccept.tsx
src/containers/Objkt/MarketplaceActions.module.scss
src/containers/Objkt/OfferCreate.tsx
src/utils/winter.ts

waiting on small fix from winter team to get the wallet address to redirect to after the purchase

feat: add winter checkout to secondary sales

---

src/utils/user.ts

add #tezquakeaid donation address

---

src/containers/Generative/Display/GenerativeDisplayIteration.module.scss

add break-word to GenerativeDisplayIteration

---

src/components/Input/Select.tsx
src/containers/Marketplace/GenerativeListings.tsx
src/containers/Settings/DisplaySettings.tsx
src/context/Theme.tsx

https://github.com/fxhash/fxhash-website/issues/554

use query param for marketplace sorting

---

src/hooks/useTransitionStyleFix.ts

temporary style fix until next 13

fix: transition style fix remove only previous stylesheet to preserve order

---

README.md
src/articles/integration-guide.md
src/doc/community/articles.md
src/doc/fxhash/integration-guide.md

complexe => complex
educationnal => educational

Fixed some typos

---

src/components/Image/Image.module.scss
src/components/Image/index.tsx
src/components/Objkt/ObjktImageAndName.module.scss

This reverts commit 9020d85e15aa043540104236ada7355435885139.

Revert "fix image component fallback when no image data"

---

src/doc/artist/fxlens.md
src/doc/artist/params.md
src/doc/collect/fxparams-mint-tickets.md
src/pages/reveal/[id].tsx

also adds `open project page` button to mint reveal

copy fixes

---

src/components/Utils/HashList.tsx
src/containers/MintGenerative/StepExtraSettings/StepExtraSettings.tsx
src/containers/MintGenerative/StepExtraSettings/VariantForm.tsx

We check if its params token we allow same hash with different params as a variant. If not params token hash must differ. Values are being displayed and truncated after 100chars

allow same hash on different params for variations

---

src/components/FxParams/BaseInput.module.scss
src/components/FxParams/BaseInput.tsx
src/components/Input/Checkbox.tsx
src/containers/MintWithTicket/MintWithTicketPage.module.scss
src/containers/MintWithTicket/MintWithTicketPage.tsx
src/containers/MintWithTicket/Panel/PanelHash.tsx
src/containers/MintWithTicket/Panel/PanelRoot.tsx
src/containers/MintWithTicket/PreMintWarning.module.scss
src/containers/MintWithTicket/PreMintWarning.tsx
src/containers/Settings/DisplaySettings.tsx
src/context/Theme.tsx
src/services/contract-operations/MintV3Abstraction.ts

feat: add pre-mint warning to mint params

---

package.json
src/components/LiveMinting/ConnectWallet.tsx
src/containers/UserProvider.tsx
src/services/Wallet.ts
yarn.lock

adds `connectAutonomyWallet` method to Wallet service which creates a fake wallet provider that routes to autonomy for signing transactions

Autonomy for live minting

---

src/containers/MintWithTicket/MintWithTicketPage.tsx
src/containers/MintWithTicket/Panel/PanelControls.tsx
src/containers/MintWithTicket/Panel/PanelRoot.tsx
src/services/contract-operations/MintV3Abstraction.ts

passing a list of tickets to the mintv3 operation will take the first available and use it. 
if there are no tickets remaining, an precise error will be displayed

fix: collector opening multiple params view can use any ticket available from close to foreclosure

---

src/components/FxParams/types.ts
src/components/FxParams/utils.ts
src/components/FxParams/validation.ts
src/containers/App.tsx
src/containers/Sandbox/Sandbox.tsx
src/hooks/useReceiveTokenInfos.ts
src/utils/snippets.ts
src/utils/tezos-storage.ts

this also requires a change in the snippet. So to test it we should merge file api PR to dev first.

allow user defined string maxlength

---

src/components/GenerativeToken/GenerativeArtwork.tsx
src/components/Tables/TableOffersSent.tsx
src/components/User/CollabBadge.module.scss
src/components/User/CollabBadge.tsx
src/containers/Homepage/HomeHero.tsx
src/containers/Homepage/RandomIterativeCycler.module.scss
src/containers/Homepage/RandomIterativeCycler.tsx
src/containers/MintWithTicket/MintWithTicketPage.tsx
src/pages/index.tsx

fix: random iterative cycler let image be clickable
fix: collab tokens in iterative cycler hide avatar as expected

fix: random iterative cycler improved ux

---

src/containers/User/Collection/Gentks.tsx
src/containers/User/UserCollectionFilters.tsx
src/types/entities/User.ts

feat: filter by listing status

---

src/components/Artwork/MintProgress.tsx

dont show reserves when completed

---

README.md
src/containers/MintWithTicket/MintWithTicketPage.module.scss
src/containers/MintWithTicket/MintWithTicketPage.tsx

add effect to temporary set html bg black

---

src/components/Utils/HoverTitle.module.scss
src/components/Utils/HoverTitle.tsx

fixes layout issues when tooltip would overflow window size

prevent tooltip out of window bounds

---

src/components/Display/DisplayTezos.tsx
src/containers/Generative/GenerativeMintTickets.tsx
src/pages/marketplace/generative/[id]/[[...tab]].tsx

- clamp lowest/highest to 2dp
- unused -> for sale in marketplace tickets table

marketplace ticket improvements

---

src/containers/Footer/Footer.module.scss
src/containers/Footer/Footer.tsx

adds an mailto link for partnerships into the footer (was requested by @qaulv)

add partnerships contact to footer

---

src/containers/Generative/Display/GenerativeDisplayIteration.tsx
src/containers/Objkt/ListingAccept.tsx

winter was never implemented for the v1 marketplace - may as well hide the option for v1 listings!

hide winter for v1 marketplace contract

---

src/components/CreditCard/CreditCardCheckout.tsx
src/components/GenerativeToken/MintButton.tsx
src/containers/Generative/Display/GenerativeDisplay.tsx
src/containers/Generative/Display/GenerativeDisplayIteration.tsx
src/containers/Objkt/ListingAccept.tsx

Reverts fxhash/fxhash-website#784

Revert "Update main"

---

src/components/Article/ArticleEvent.module.scss
src/pages/events/[id]/onboarding.module.scss
src/pages/events/[id]/onboarding.tsx
src/styles/globals.scss

as requested by charlie, go to:
https://fxhash-git-feat-cleanup-onboarding-css-fxhash.vercel.app/events/hackathon-test/onboarding
to see if there are any other changes to be made?

cleanup onboarding css
