- src/components/Utils/ClientOnly.tsx
Objective:
drop `ClientOnly` / `ClientOnlyEmpty`'s own implementation of isMounted check in favor of `useIsMounted` hook
Thanks for the clean and very readable code base and I do learn from it a lot :) 
Notes:
* I don't seem to find any tests being setup so it's probably too early to do this, please let me know if adding few tests would be appropriate atm
* It's uncertain to me if `hookts` is named this way intentionally so I just keep it
> chore: leverage useIsMounted hook

- src/components/Artwork/PreviewIframe.tsx
Adding allow property to iframes to allow for access to various browser APIs from cross-domain iframes.
Allows for access to:
- accelerometer
- camera
- gyroscope
- microphone
- xr-spatial-tracking;
> Update preview iframe allow permissions

- src/pages/community/reports.tsx
community reports page always hit the backend to retrieve content. Currently it's a public page and all members / visotrs might see the same content regardless. We can build the page and always serve the cache when appropriate and rebuild page periodically.
> ✨ optimize community reports page

- src/components/Card/GenerativeTokenCard.tsx
Adding price to explore page, so that users can easilly decide which pieces stand out based on interest and price. Without having to open every piece to find out the price.
> Added price to generative card so it displays on Explore Page.

- src/utils/hookts.ts
profileVerification links were not always updated when navigating between users or when using browser history.
> profileVerification mix bug correction

- src/containers/Explore/LiveFeed.tsx
Fixed a minor typo on the reveal feed (~revelead~ revealed):
> Bug: Fixed minor typo on reveal feed page

- src/components/User/UserBadge.tsx
I'm referring to this error:
https://user-images.githubusercontent.com/3226096/164323669-1ece5d0f-a403-460a-9e5c-75769920d834.mp4
steps to reproduce:
- open project page
- click on the "activity" tab
- scroll until error
it happens because actions of type `UPDATE_PRICING` and `UPDATE_STATE` have a `null` issuer, and the component `UserBadge` doesn't check if the user is `null`
(it happens only if in the fetched actions there are some of type `UPDATE_PRICING` and `UPDATE_STATE`, that's why on some pages it doesn't happen or it crashes only after older data is fetched while scrolling)
My solution: don't show UserBadge if user is undefined
I know it is not really a front-end issue because the issuer should (probably) always be returned, but this way it can't crash if it doesn't (like it does …
> Bugfix for error while scrolling a token's activity list

- src/components/Input/SearchInputControlled.tsx
- src/containers/Marketplace.tsx
- src/pages/_app.tsx
- src/pages/marketplace.tsx
Now (on the marketplace page) all the search filter are added to the URL as parameters:
https://user-images.githubusercontent.com/3226096/164341893-0cf2ac9a-868c-43af-89c9-a4a4b9c04f31.mp4
The url can be shared and the filters will be restored when the page loads
There is still a small "bug" (also in production), when you search some text and then clear the filter, the text inside the input is not cleared:
https://user-images.githubusercontent.com/3226096/164342185-f9f45a63-3c05-4758-b3ca-6b47d04c0e28.mp4
> Appends marketplace search filters to URL. Closes #30

- src/containers/ExploreGenerativeTokens.tsx
- src/containers/Generative/ExploreIncoming.tsx
- src/queries/user.ts
resolves #61 
(shows only the progress, not the numeric amount of reserves)
> Show reserves progress bar in tokens cards in the explore page

- src/containers/Generative/Enjoy/GenerativeEnjoy.tsx
- src/containers/User/Enjoy/UserCollectionEnjoy.tsx
- src/queries/user.ts
@ciphrd I implemented a separate `Qu_userEntireCollection` for the enjoy collection because `Qu_userObjkts` i also used in the normal user collection page and i guess there it makes sense to keep paginated objkts. let me know what you think
- fix #86
> add graphql for user entire collection

- src/components/Artwork/PreviewIframe.tsx
fixes #31 
Using `iframe.contentWindow.location.replace(newUrl)` doesn't add the iframe history to the main one!
_Source: https://html.spec.whatwg.org/multipage/iframe-embed-object.html#dom-iframe-contentwindow_
> keep iframe history hidden on gentk variation

- src/components/User/CollabBadge.module.scss
- src/components/User/CollabBadge.tsx
- src/pages/gentk/[...params].tsx
fix #105 
I encountered this kind of bug in the past, server-side shuffle and client-side shuffle have a different result which mix the results when rehydrating. 
A simple fix is to run the randomisation only on the client-side (using useEffect)
> fix(collab-badge): randomize client-side only to avoid rehydration issues

- src/components/Stats/GenerativeRank.tsx
- src/queries/stats.ts
@ciphrd shall we add this feature to the `getUserName` util?  shall names be alphabetically ordered or as they come?
- fix #109
> resolve collaborator names on marketplace ranks

- src/components/Artwork/MintProgress.tsx
- src/queries/generative-token.ts
reserve progress width was wrong when the burnt edition weren't shown
solves #155
> fixed reserveProgress calculation

- src/components/NFTArticle/processor/getMarkdownFromSlateEditorState.ts
- fix #296
markdown string looks like this when using bulletOther option:
> use bulletOther option to avoid comments between lists

- src/components/Card/CardNFTArticle.module.scss
- src/containers/Explore/ExploreArticles.module.scss
- src/pages/explore/articles.tsx
- fix #353 
Float the date of the article cards below the author. 
@ciphrd card witdth was already as the token cards. Shall we also respect the "gap between cards" user setting for the spacing between article cards?
> Fix/article: card responsive

- src/components/Card/CardNFTArticle.module.scss
- src/components/Card/CardNFTArticle.tsx
- src/containers/Article/LocalArticles.tsx
Found a bug on the user/articles page, unpublished changes buttons trigger a on delete that does nothing.
This commit fix the button behavior (goes to page edition of the article), and add a new button to delete the unpublished changes.
> fix(article): card nft article have buttons working as intended -> edit goes to article edit page, bin delete the local changes

- public/sandbox/worker.js
- fix #246
set proper mimetype for js files and fetch module files if referrer differs but file is part of cache. 
If you don't have a js module project you can use this zip to test it:
[Archive.zip](https://github.com/fxhash/fxhash-website/files/9455112/Archive.zip)
> allow js modules in the sandbox

- src/pages/article/editor/local/[id]/preview.tsx
@ciphrd wrong query params resultet in user query never being resolved and therefore the `royaltiesSplits` was always empty preventing the possibility to mint articles.  
mentioned in discord by ErikWestener:
> when possible can someone check errors on fxtext. A few folks are unable to mint new pieces, myself included.  Attempting on multiple browsers, clearing cache, etc. -- I know it's not much to go on but error is below.
> fix error on users query due to wrong params

- src/containers/Article/PageArticle.module.scss
> fix: article figcaption have his audio/video/img element centered if bigger

- src/styles/globals.scss
Modals and anything using portal wouldn't have their default color set to --color-black, meaning that they would still be default browser color when using dark-mode. This PR fix that
> fix: modal and portal get correct font-color

- src/containers/Footer/Footer.tsx
- fix #489 
for now we are linking to notion v1. 
we can create a design for a designated page that can be implemented in v2?
> add link to notion presskit

- src/components/Input/Select.tsx
- fix #503 
We are using a `<Cover />` component when select is open that handles closing the open select dialog when you click anywhere. Since the `<Cover />` lays ontop of the scrollable area the scroll event doesn't arrive in the scrollable container. 
I removed the `Cover` from the `Select` component and replaced it with the `clickOutsideHook`
> replace cover with useClickOutside hook

- src/containers/Presskit/Page.tsx
When navigating through the presskit tabs, the effect wouldn't recognise if the user would navigate to the "root" tab via back buttons of the browser because in that case the slug is undefined and the effect would be skipped.
> presskit page: fix issue where router change to root tab would be ignored

- src/components/Display/DisplayTezos.module.scss
- src/components/GenerativeToken/MintController.module.scss
> fix word break for DisplayTezos on narrow devices

- src/components/Tables/TableMintTickets.tsx
- src/components/Tables/TableUser.module.scss
- src/containers/User/Collection/Tickets.tsx
- src/containers/User/UserCollection.tsx
- src/pages/u/[name]/collection/tickets.tsx
- src/queries/user.ts
re-uses the same table as on the token page therefore sensitive for which actions it shows based on the profile:
> add tickets tab to user collection

- src/components/Artwork/MintProgress.tsx
check `/generative/slug/hello-test` for before/after behaviour
> fix overflowing reserves after supply is burnt

- src/components/User/CollabBadge.module.scss
- src/components/User/CollabBadge.tsx
- fix #546 
This PR adds `maxCollaborators: number` prop to collabbadge. its defaulting to 5. i added some ref magic to ensure the toggle button will overflow the +xxx circle independent of its size.
closing #548 in favor of this pr
> add maxCollaborators prop for collabbadge truncation

- src/hooks/useIsMobile.ts
There is no menu rendered on breakpoint md because the `useIsMobile` hook had sm breakpoint as default value. I've changed the default mobile breakpoint to md.
> Fix no menu on breakpoint md

- src/hooks/useMintingState.ts
on mint state hook we used the opening date as interval which can be way in the future. 
> Browsers store the delay as a 32-bit signed integer internally. This causes an integer overflow when using delays larger than 2,147,483,647 ms (about 24.8 days), resulting in the timeout being executed immediately.
this caused a memory leak e.g. on explore incoming. i haven't checked if we have similar cases somewhere on the site.
> fix memory leak caused by integer overflow

- src/components/CreditCard/CreditCardCheckout.tsx
- src/components/GenerativeToken/MintButton.tsx
passing `recipient` does not enable other wallets to consume reserves on behalf of the reserve holder, so we still can't facilitate access list reserves thru winter
> disable using access list reserves with winter

- src/components/GenerativeToken/MintButton.tsx
- src/components/GenerativeToken/MintController.tsx
we still want to show the winter option when the user has access list reserve - but we don't want to attempt to use the reserve so avoid passing to `CreditCardCheckout`
> fix winter / access list reserve logic

- src/containers/MintWithTicket/Panel/PanelControls.tsx
seems like when the user has reserves for a project and click use ticket, we are attempting to show the reserve dropdown (which is hidden because you're using a ticket) so nothing happens in the UI...this should fix
> fix use ticket with reserves bug

- src/containers/Generative/Redeem/GenerativeRedeem.tsx
- src/pages/generative/[...params].tsx
- src/pages/generative/[id]/redeem.tsx
- src/pages/gentk/[...params].tsx
- src/pages/gentk/[id]/redeem/[address].tsx
- src/pages/gentk/[id]/redeem/index.tsx
we can't delete redeemables in the backend rn so to avoid having multiple broken redeemables displayed in the frontend, this pr filters out all redeemables that have been made inactive from the UI. once we implement proper deletion of redeemables these manual fixes can be removed
> temporarily filter inactive redeemables

- src/components/Artwork/PreviewIframe.tsx
- src/components/Artwork/SandboxPreview.tsx
- src/containers/MintGenerative/StepCheckFiles.tsx
It was reported that camera wasn't working. There were two issues:
- We need `allow-modals` so the iframe can actually trigger the modal to set permission for camera usage
- We also needed to set the allow_list for the features we allow for cross origin to allow in top-level browsing contexts and in nested contexts (iframes)
Reference: https://blog.addpipe.com/camera-and-microphone-access-in-cross-oirigin-iframes-with-feature-policy/
Aside from that we are now also always just rendering one iframe per breakpoint instead of hiding them via css
> set allow-modals and * allow_list for allowed features

- src/containers/MintWithTicket/MintWithTicketPage.tsx
when a project doesn't have the snippetVersion in the metadata we have to explicitly fallback to 3.2.0 in order to use the old format of putting inputbytes in the query params
- Click the params button below the artwork on dev it doesnt open with the input bytes already set but random: https://dev.fxhash-dev.xyz/gentk/FX1-1333
- Here the same link on this branch works: https://fxhash-git-fix-apply-default-snippet-version-when-99d0e5-fxhash.vercel.app/gentk/FX1-1333
> fallback to 3.2.0 snippetVersion on old projects
